services:

  backend:
    build: ./backend
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=QuotesDb;User Id=sa;Password=MyStrongPassword123!;TrustServerCertificate=true;

  db-init:
    build: ./DbInitialization
    depends_on:
      - backend
      - mssql

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword123!
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
